// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: connstatsprotobuf/connstats.proto

package connstatsprotobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol   string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	LIp        string `protobuf:"bytes,2,opt,name=l_ip,json=lIp,proto3" json:"l_ip,omitempty"` //netip.Addr
	RIp        string `protobuf:"bytes,3,opt,name=r_ip,json=rIp,proto3" json:"r_ip,omitempty"` //netip.Addr
	LPort      uint32 `protobuf:"varint,4,opt,name=l_port,json=lPort,proto3" json:"l_port,omitempty"`
	RPort      uint32 `protobuf:"varint,5,opt,name=r_port,json=rPort,proto3" json:"r_port,omitempty"`
	PacketsIn  uint32 `protobuf:"varint,6,opt,name=packets_in,json=packetsIn,proto3" json:"packets_in,omitempty"`
	PacketsOut uint32 `protobuf:"varint,7,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`
	TsStart    uint64 `protobuf:"varint,8,opt,name=ts_start,json=tsStart,proto3" json:"ts_start,omitempty"`
	TsCurrent  uint64 `protobuf:"varint,9,opt,name=ts_current,json=tsCurrent,proto3" json:"ts_current,omitempty"`
	BytesIn    uint64 `protobuf:"varint,10,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut   uint64 `protobuf:"varint,11,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
}

func (x *ConnectionStat) Reset() {
	*x = ConnectionStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connstatsprotobuf_connstats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStat) ProtoMessage() {}

func (x *ConnectionStat) ProtoReflect() protoreflect.Message {
	mi := &file_connstatsprotobuf_connstats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStat.ProtoReflect.Descriptor instead.
func (*ConnectionStat) Descriptor() ([]byte, []int) {
	return file_connstatsprotobuf_connstats_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionStat) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectionStat) GetLIp() string {
	if x != nil {
		return x.LIp
	}
	return ""
}

func (x *ConnectionStat) GetRIp() string {
	if x != nil {
		return x.RIp
	}
	return ""
}

func (x *ConnectionStat) GetLPort() uint32 {
	if x != nil {
		return x.LPort
	}
	return 0
}

func (x *ConnectionStat) GetRPort() uint32 {
	if x != nil {
		return x.RPort
	}
	return 0
}

func (x *ConnectionStat) GetPacketsIn() uint32 {
	if x != nil {
		return x.PacketsIn
	}
	return 0
}

func (x *ConnectionStat) GetPacketsOut() uint32 {
	if x != nil {
		return x.PacketsOut
	}
	return 0
}

func (x *ConnectionStat) GetTsStart() uint64 {
	if x != nil {
		return x.TsStart
	}
	return 0
}

func (x *ConnectionStat) GetTsCurrent() uint64 {
	if x != nil {
		return x.TsCurrent
	}
	return 0
}

func (x *ConnectionStat) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *ConnectionStat) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

// The request message.
type StatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connstatsprotobuf_connstats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connstatsprotobuf_connstats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_connstatsprotobuf_connstats_proto_rawDescGZIP(), []int{1}
}

// The response message containing the stats table
type StatsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connstat []*ConnectionStat `protobuf:"bytes,1,rep,name=connstat,proto3" json:"connstat,omitempty"`
}

func (x *StatsReply) Reset() {
	*x = StatsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connstatsprotobuf_connstats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReply) ProtoMessage() {}

func (x *StatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_connstatsprotobuf_connstats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReply.ProtoReflect.Descriptor instead.
func (*StatsReply) Descriptor() ([]byte, []int) {
	return file_connstatsprotobuf_connstats_proto_rawDescGZIP(), []int{2}
}

func (x *StatsReply) GetConnstat() []*ConnectionStat {
	if x != nil {
		return x.Connstat
	}
	return nil
}

var File_connstatsprotobuf_connstats_proto protoreflect.FileDescriptor

var file_connstatsprotobuf_connstats_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0xb2, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x11, 0x0a, 0x04, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x49, 0x70, 0x12, 0x11, 0x0a, 0x04, 0x72, 0x5f, 0x69, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x49, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x6c,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x49, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x73, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x73, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x73, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x73, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x79, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3d, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x6e, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f,
	0x6e, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x32, 0x60, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x63, 0x6f,
	0x6e, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connstatsprotobuf_connstats_proto_rawDescOnce sync.Once
	file_connstatsprotobuf_connstats_proto_rawDescData = file_connstatsprotobuf_connstats_proto_rawDesc
)

func file_connstatsprotobuf_connstats_proto_rawDescGZIP() []byte {
	file_connstatsprotobuf_connstats_proto_rawDescOnce.Do(func() {
		file_connstatsprotobuf_connstats_proto_rawDescData = protoimpl.X.CompressGZIP(file_connstatsprotobuf_connstats_proto_rawDescData)
	})
	return file_connstatsprotobuf_connstats_proto_rawDescData
}

var file_connstatsprotobuf_connstats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_connstatsprotobuf_connstats_proto_goTypes = []interface{}{
	(*ConnectionStat)(nil), // 0: connstatsprotobuf.ConnectionStat
	(*StatsRequest)(nil),   // 1: connstatsprotobuf.StatsRequest
	(*StatsReply)(nil),     // 2: connstatsprotobuf.StatsReply
}
var file_connstatsprotobuf_connstats_proto_depIdxs = []int32{
	0, // 0: connstatsprotobuf.StatsReply.connstat:type_name -> connstatsprotobuf.ConnectionStat
	1, // 1: connstatsprotobuf.StatsService.CollectStats:input_type -> connstatsprotobuf.StatsRequest
	2, // 2: connstatsprotobuf.StatsService.CollectStats:output_type -> connstatsprotobuf.StatsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connstatsprotobuf_connstats_proto_init() }
func file_connstatsprotobuf_connstats_proto_init() {
	if File_connstatsprotobuf_connstats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connstatsprotobuf_connstats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connstatsprotobuf_connstats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connstatsprotobuf_connstats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connstatsprotobuf_connstats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connstatsprotobuf_connstats_proto_goTypes,
		DependencyIndexes: file_connstatsprotobuf_connstats_proto_depIdxs,
		MessageInfos:      file_connstatsprotobuf_connstats_proto_msgTypes,
	}.Build()
	File_connstatsprotobuf_connstats_proto = out.File
	file_connstatsprotobuf_connstats_proto_rawDesc = nil
	file_connstatsprotobuf_connstats_proto_goTypes = nil
	file_connstatsprotobuf_connstats_proto_depIdxs = nil
}
